DLUserBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'preference', 'auth-token']
        prenom:
            groups: ['user', 'preference', 'auth-token']
        nom:
            groups: ['user', 'preference', 'auth-token']
        email:
            groups: ['user', 'preference', 'auth-token']
        preferences:
            groups: ['user']

DLUserBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']