dl_commission:
    resource: "@DLCommissionBundle/Resources/config/routing.yml"
    prefix:   /


dl_achat:
    resource: "@DLAchatBundle/Resources/config/routing.yml"
    prefix:   /

dl_user:
    resource: "@DLUserBundle/Resources/config/routing.yml"
    prefix:   /

dl_backoffice:
    resource: "@DLBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

#test_rest
user:
    resource: "@DLUserBundle/Controller/UserController.php"
    prefix:   /
    type:     rest

#achat rest
achat:
    resource: "@DLAchatBundle/Controller/AchatController.php"
    prefix:   /
    type:     rest

#inscription_rest
inscription:
    resource: "@DLUserBundle/Controller/InscriptionController.php"
    prefix:   /
    type:     rest

#JWT_login
api_login_check:
    path: /api/login_check


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#Authentification

auth-tokens:
    resource: "@DLUserBundle/Controller/AuthTokenController.php"
    type:     rest



#arbo_rest
tree:
    resource: "@DLCommissionBundle/Controller/ArboController.php"
    prefix:   /
    type:     rest

product:
    resource: "@DLAchatBundle/Controller/ProductController.php"
    prefix:   /
    type:     rest