dl_commission:
    resource: "@DLCommissionBundle/Resources/config/routing.yml"
    prefix:   /

dl_achat:
    resource: "@DLAchatBundle/Resources/config/routing.yml"
    prefix:   /

dl_user:
    resource: "@DLUserBundle/Resources/config/routing.yml"
    prefix:   /

dl_backoffice:
    resource: "@DLBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@DLUserBundle/Controller/UserController.php"
    prefix:   /
    type:     rest

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation


