services:
#    dl_commission.example:
#        class: DL\CommissionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
# src/OC/PlatformBundle/Resources/config/services.yml
     dl_commission.test:
         class: DL\CommissionBundle\Service\TestService
         arguments: [ "@doctrine.orm.entity_manager" ]
     dl_commission.law:
              class: DL\CommissionBundle\Service\ProbcomService
              arguments: [ "@doctrine.orm.entity_manager" ]
     dl_commission.partner:
                   class: DL\CommissionBundle\Service\RLService
                   arguments: [ "@doctrine.orm.entity_manager" ]